[package]
name = "rust-todo-list"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.8.0"
serde = { version = "1.0.203", features = ["derive"] }
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["full"] }
axum-server = "0.6.0"